# Báo cho Travis biết dùng Java
language: java

# Báo cho Travis dùng Java 17
jdk:
  - openjdk17

# Lệnh chạy test
script:
  - ./mvnw clean package

# Cache lại thư viện cho lẹ
cache:
  directories:
    - $HOME/.m2