# Tên của workflow
name: Java CI (Test PetClinic)

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Kéo code về
      uses: actions/checkout@v4

    # BƯỚC SỬA LỖI ĐÂY:
    - name: "Setup Java 25 (Theo yêu cầu)" # <-- Đổi tên cho rõ
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'     
        java-version: '25'        # <-- CHỐT HẠ LÀ 25

    - name: Chạy test bằng Maven
      run: ./mvnw clean package